import { handleAIRequest } from "../utils/ai.js";

export async function processDetector(input, userModel, env) {
  // 1. Enforce a stronger model for detection if possible
  // Detection requires high reasoning. If userModel is weak/fast, 
  // you might want to force a larger model like llama-3.3-70b-versatile
  const modelToUse = userModel || "llama-3.3-70b-versatile"; 

  const SYSTEM_PROMPT = `
    You are an expert Linguistic Forensic Analyst. 
    
    TASK:
    Analyze the provided text to determine if it was written by a Human or generated by an AI (LLM).

    ANALYSIS CRITERIA:
    1. **Burstiness & Sentence Variance**: Humans vary sentence length drastically (short, then long and complex). AI is often monotonous and rhythmic.
    2. **Perplexity/Vocabulary**: Humans use idioms, slang, and unexpected words. AI uses "safe", high-probability words.
    3. **Structure**: AI often uses listicles, heavy transition words ("Furthermore", "In conclusion"), and perfectly balanced paragraphs.
    4. **Nuance**: Humans express strong opinions, specific personal anecdotes, or logical leaps. AI is often neutral, hedging, and generic.

    SCORING GUIDE:
    - 0-30%: Likely Human (High burstiness, typos, specific anecdotes, irregular structure).
    - 31-70%: Uncertain/Mixed (Polished human text or heavily prompted AI).
    - 71-100%: Likely AI (Perfect grammar, repetitive structure, lack of depth, overuse of transition words).

    OUTPUT FORMAT (STRICT JSON):
    {
      "ai_probability": number (integer 0-100),
      "confidence": "low" | "medium" | "high",
      "reasoning": "A 1-sentence analytical explanation focusing on sentence structure and vocabulary."
    }

    RULES:
    - If the text is extremely short (< 20 words), set confidence to "low".
    - Do NOT be afraid to give a low score if it feels human.
    - Return ONLY valid JSON.
  `;

  // Explicitly use Key 4
  const apiKey = env.GROQ_API_KEY_4;

  return await handleAIRequest(apiKey, SYSTEM_PROMPT, input, modelToUse, temperature = 0.5);
}